### ISSUE TITLE
bug!???

### ISSUE THREAD

**Issue by huitc** [s0md3v/Breacher#14]
`python2 breacher.py --fast -u "www.test.com.us/tc/"`
```
--------------------------------------------------------------------------

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "breacher.py", line 100, in part2
    scan(links) #calls the scanner
  File "breacher.py", line 52, in scan
    r = requests.get(link) #Requests to the combined url
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='www.test.com.ustc', port=80): Max retries exceeded with url: /admin/welcome.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7248e77e10>: Failed to establish a new connection: [Errno 7] No address associated with hostname',))
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "breacher.py", line 97, in part1
    scan(links) #calls the scanner
  File "breacher.py", line 52, in scan
    r = requests.get(link) #Requests to the combined url
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='www.test.com.ustc', port=80): Max retries exceeded with url: /acceso.asp (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7248e77c10>: Failed to establish a new connection: [Errno 7] No address associated with hostname',))


$
```

**Comment by s0md3v** [comment]
Dude the website you are testing against doesn't even exist.

**Comment by s0md3v** [comment]
PS: In case you redacted the website for privacy, it's still not Breacher's fault. The target website is timing out.

**Comment by huitc** [comment]
i can't test a website like this?`xxx.com/tc/`

**Comment by huitc** [comment]
first page `www.test.com.us/tc/index.php`
